version: '3'
#Each container is called a service
services:
  node-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - PORT=5000
    # env_file:
    #   - ./.env

    